repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.1.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.9.1
  hooks:
    - id: check-github-workflows
    - id: check-readthedocs
- repo: https://github.com/python/black
  rev: 21.12b0
  hooks:
    - id: black
      name: "Autoformat python files"
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.0
  hooks:
    - id: blacken-docs
      additional_dependencies: ['black==21.12b0']
- repo: https://github.com/asottile/dead
  rev: v1.4.0
  hooks:
    - id: dead
      # run `dead` only on specific files, where
      # (1) `dead` is passing
      # (2) the structure of the code makes extra unused variable detection
      #     useful (e.g. subclasses which *must* pass arguments to their
      #     superclasses or risk silently swallowing/ignoring arguments)
      # (3) we are prepared to commit to keeping `dead` happy and using
      #     `# dead: disable` comments as needed
      args:
        - "--files"
        - |
          (?x)^(
            src/globus_sdk/services/gcs/data.py|
            src/globus_sdk/services/transfer/data/delete_data.py|
            src/globus_sdk/services/transfer/data/transfer_data.py
          )
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      name: "Lint python files"
      additional_dependencies: ['flake8-bugbear==21.11.29']
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: "Sort python imports"
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
    - id: mypy
      files: ^src/globus_sdk/
      additional_dependencies:
        - types-docutils
        - types-jwt
        - types-requests
