sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py,lowestdeps
    # py2 linting build (flake8 on py2 can flag different stuff)
    - python: "2.7"
      env: TOXENV=lint
    # test on 3.4, 3.5, 3.6
    - python: "3.4"
      env: TOXENV=py
    - python: "3.5"
      env: TOXENV=py
    - python: "3.6"
      env: TOXENV=py,lowestdeps
    # separate py3.6 linting build, which runs 'black --check' (no py2 support)
    - python: "3.6"
      env: TOXENV=py36-lint
    # hack py37, py38 to use a different Travis worker type
    # sudo:required gets us the VM builds where these pythons work
    - python: "3.7"
      env: TOXENV=py
      sudo: required
    # TODO: re-evaluate these
    # 3.8-dev and nightly don't support flake8
    # travis pypy builds seem to have been busted
    - python: "3.8-dev"
      env: TOXENV=py
      sudo: required
    - python: "pypy"
      env: TOXENV=py
    - python: "pypy3"
      env: TOXENV=py
    - python: "nightly"
      env: TOXENV=py
    # windows testing
    - os: windows
      language: sh
      python: "2.7"
      env: TOXENV=py,lowestdeps,lint
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: "3.7"
      env: TOXENV=py,lowestdeps,py37-lint
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
  allow_failures:
    - python: "3.8-dev"
    - python: "pypy"
    - python: "pypy3"
    - python: "nightly"
cache: pip
install:
  - pip install -e '.[development]'
script:
  - tox
